spring.application.name=MedicalChatEMR
spring.config.import=optional:application-local.properties
# 'WEB-INF/views/' ëë í ë¦¬ ìì .jspíì¼ì ë·°ë¡ ì¬ì©íê²íë ì¤ì 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# application.properties
#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=true
#spring.http.encoding.force=true


#ë°ì´í°ë² ì´ì¤ ì°ê²°
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/EMR}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ì¤ì 
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# open api key
api.key=${API_KEY:}
api.drug.url=http://apis.data.go.kr/1471000/DayMaxDosgQyByIngdService/getDayMaxDosgQyByIngdInq

## 클래스패스 변경 시 자동 재시작 활성화 또는 비활성화
#spring.devtools.restart.enabled=true
#
## 라이브 리로드(브라우저 새로고침) 활성화 또는 비활성화
#spring.devtools.livereload.enabled=true

# 재시작을 감지할 디렉토리 설정
spring.devtools.restart.additional-paths=src/main/webapp

